# Start from a Node base image
FROM node:latest
# Set the working directory
WORKDIR /app
# Set environment variables
ARG CLIENT_ID
ENV CLIENT_ID=${CLIENT_ID}
ARG BACKEND_URL
ENV BACKEND_URL=${BACKEND_URL}
ARG AVATAR_API
ENV AVATAR_API=${AVATAR_API}
# Copy package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy the rest of the code
COPY . .
# Build the app
RUN npm run build
# Expose the port the app runs on
EXPOSE 3000
# Start the application
CMD ["npm", "start"]

